CREATE FUNCTION fnUltrapassaram(@Data VARCHAR(7))
RETURNS TABLE AS
RETURN(
	SELECT 
		TC.CPF,
		TC.NOME,
		TC.VOLUME_DE_COMPRA,
		CONVERT(VARCHAR(7), NF.DATA_VENDA, 120) AS "MÊS E ANO",
		SUM(INF.QUANTIDADE) as Quantidade,
		CASE 
			WHEN (SUM(INF.QUANTIDADE) <= TC.VOLUME_DE_COMPRA) THEN 'VENDAS VÁLIDAS' 
			ELSE 'VENDAS INVÁLIDAS'
		END AS RESULTADO

	FROM TABELA_DE_CLIENTES AS TC
	INNER JOIN NOTAS_FISCAIS AS NF
	ON TC.CPF = NF.CPF
	INNER JOIN ITENS_NOTAS_FISCAIS INF
	ON INF.NUMERO = NF.NUMERO
	WHERE CONVERT(VARCHAR(7), NF.DATA_VENDA, 120) = @Data
	GROUP BY NF.CPF, TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA, CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)
	)


	SELECT * FROM fnUltrapassaram('2015-01')
