CREATE FUNCTION fnUltrapassaram(@Data VARCHAR(7))
RETURNS TABLE AS
RETURN(
	SELECT 
		TC.CPF,
		TC.NOME,
		TC.VOLUME_DE_COMPRA,
		SUM(CASE WHEN NF.CPF = TC.CPF THEN ()) AS 'QUANTIDADE_TOTAL'
		
	FROM TABELA_DE_CLIENTES AS TC
	INNER JOIN NOTAS_FISCAIS AS NF
	ON TC.CPF = NF.CPF
	SELECT
		SUM(INF.QUANTIDADE) as Quantidade
	FROM ITENS_NOTAS_FISCAIS INF
	INNER JOIN NOTAS_FISCAIS NF
	ON INF.NUMERO = NF.NUMERO
	GROUP BY NF.CPF
	ORDER BY NF.CPF ASC
	)
