CREATE FUNCTION fnUltrapassaram(@Data VARCHAR(7))
RETURNS TABLE AS
RETURN(
	SELECT 
		TC.CPF,
		TC.NOME,
		TC.VOLUME_DE_COMPRA,
		CONVERT(VARCHAR(7), NF.DATA_VENDA, 120) AS "MÊS E ANO",
		SUM(INF.QUANTIDADE) as Quantidade,
		CASE 
			WHEN (SUM(INF.QUANTIDADE) <= TC.VOLUME_DE_COMPRA) THEN 'VENDAS VÁLIDAS' 
			ELSE 'VENDAS INVÁLIDAS'
		END AS RESULTADO

	FROM TABELA_DE_CLIENTES AS TC
	INNER JOIN NOTAS_FISCAIS AS NF
	ON TC.CPF = NF.CPF
	INNER JOIN ITENS_NOTAS_FISCAIS INF
	ON INF.NUMERO = NF.NUMERO
	WHERE CONVERT(VARCHAR(7), NF.DATA_VENDA, 120) = @Data
	GROUP BY NF.CPF, TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA, CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)
	)


	SELECT * FROM fnUltrapassaram('2015-01')



alter FUNCTION fnPorcentagem(@Data VARCHAR(4))
RETURNS TABLE AS
RETURN(
	SELECT 
		TP.SABOR,
		CONVERT(VARCHAR(4), NF.DATA_VENDA, 120) AS ANO,
		SUM(INF.QUANTIDADE) as VENDA_ANO,
		ROUND(SUM(INF.QUANTIDADE)/(SELECT dbo.fnTotalA(@Data)) * 100, 2) AS TOTAL
	FROM ITENS_NOTAS_FISCAIS AS INF
	RIGHT JOIN TABELA_DE_PRODUTOS AS TP
	ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
	INNER JOIN NOTAS_FISCAIS AS NF
	ON NF.NUMERO = INF.NUMERO

	WHERE CONVERT(VARCHAR(4), NF.DATA_VENDA, 120) = @Data
	GROUP BY TP.SABOR, CONVERT(VARCHAR(4), NF.DATA_VENDA, 120)
	ORDER BY VENDA_ANO DESC
)

select * from fnPorcentagem('2015')

	CREATE FUNCTION fnTotalA(@Data VARCHAR(4))
	RETURNS FLOAT AS 
	BEGIN RETURN (
		SELECT TOP 1 SUM(INF.QUANTIDADE) AS 'TOTAL ANO' 
		FROM ITENS_NOTAS_FISCAIS AS INF
		INNER JOIN NOTAS_FISCAIS AS NF
		ON INF.NUMERO = NF.NUMERO
		WHERE CONVERT(VARCHAR(4), NF.DATA_VENDA, 120) = @Data
	) END

	SELECT dbo.fnTotalA('2015')
